server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
  instance:
    hostname: localhost

spring:
  application:
    name: proxy-service
  config :
    import : optional:config-server
  cloud:

    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
