server:
  port: 9999
eureka:

  instance:
    hostname: localhost

spring:
  application:
    name: proxy-service
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
